map_banners = {
    "BF3": {
        "MP_001": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_001/01.jpg",
        "MP_003": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_003/01.jpg",
        "MP_007": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_007/01.jpg",
        "MP_011": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_011/01.jpg",
        "MP_012": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_012/01.jpg",
        "MP_013": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_013/01.jpg",
        "MP_017": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_017/01.jpg",
        "MP_018": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_018/01.jpg",
        "MP_Subway": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/MP_Subway/01.jpg",
        "XP1_001": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP1_001/01.jpg",
        "XP1_002": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP1_002/01.jpg",
        "XP1_003": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP1_003/01.jpg",
        "XP1_004": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP1_004/01.jpg",
        "XP2_Palace": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP2_Palace/01.jpg",
        "XP2_Office": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP2_Office/01.jpg",
        "XP2_Factory": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP2_Factory/01.jpg",
        "XP2_Skybar": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP2_Skybar/01.jpg",
        "XP3_Alborz": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP3_Alborz/01.jpg",
        "XP3_Shield": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP3_Shield/01.jpg",
        "XP3_Desert": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP3_Desert/01.jpg",
        "XP3_Valley": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP3_Valley/01.jpg",
        "XP4_Parl": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP4_Parl/01.jpg",
        "XP4_Quake": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP4_Quake/01.jpg",
        "XP4_FD": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP4_FD/01.jpg",
        "XP4_Rubble": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP4_Rubble/01.jpg",
        "XP5_001": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP5_001/01.jpg",
        "XP5_002": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP5_002/01.jpg",
        "XP5_003": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP5_003/01.jpg",
        "XP5_004": "https://cdn.jsdelivr.net/gh/kaloczikvn/VU-Loading-Images@master/XP5_004/01.jpg",
    },
    "BF2142": {
        "belgrade": "http://2142-dev.com/belgrade.png",
        "bridge_at_remagen": "http://2142-dev.com/bridgeatremagen.png",
        "camp_gibraltar": "http://2142-dev.com/campgibraltar.png",
        "cerbere_landing": "http://2142-dev.com/cerberelanding.png",
        "fall_of_berlin": "http://2142-dev.com/fallofberlin.png",
        "highway_tampa": "http://2142-dev.com/highwaytampa.png",
        "liberation_of_leipzig": "http://2142-dev.com/liberationofleipzig.png",
        "minsk": "http://2142-dev.com/minsk.png",
        "molokai": "http://2142-dev.com/molokai.png",
        "operation_blue_pearl": "http://2142-dev.com/operationbluepearl.png",
        "operation_shingle": "http://2142-dev.com/operationshingle.png",
        "port_bavaria": "http://2142-dev.com/portbavaria.png",
        "shuhia_taiba": "http://2142-dev.com/shuhiataiba.png",
        "sidi_power_plant": "http://2142-dev.com/sidipowerplant.png",
        "strike_at_karkand": "http://2142-dev.com/strikeatkarkand.png",
        "suez_canal": "http://2142-dev.com/suezcanal.png",
        "tunis_harbor": "http://2142-dev.com/tunisharbor.png",
        "verdun": "http://2142-dev.com/verdun.png",
        "wake_island_2142": "http://2142-dev.com/wakeisland.png",
        "yellow_knife": "http://2142-dev.com/yellowknife.png",
    }
}

map_names = {
    "BF3": {
        "MP_001": "Grand Bazaar",
        "MP_003": "Teheran Highway",
        "MP_007": "Caspian Border",
        "MP_011": "Seine Crossing",
        "MP_012": "Operation Firestorm",
        "MP_013": "Damavand Peak",
        "MP_017": "Noshahr Canals",
        "MP_018": "Kharg Island",
        "MP_Subway": "Operation Métro",
        "XP1_001": "Strike at Karkand",
        "XP1_002": "Gulf of Oman",
        "XP1_003": "Sharqi Peninsula",
        "XP1_004": "Wake Island",
        "XP2_Palace": "Donya Fortress",
        "XP2_Office": "Operation 925",
        "XP2_Factory": "Scrapmetal",
        "XP2_Skybar": "Ziba Tower",
        "XP3_Alborz": "Alborz Mountains",
        "XP3_Shield": "Armored Shield",
        "XP3_Desert": "Bandar Desert",
        "XP3_Valley": "Death Valley",
        "XP4_Parl": "Azadi Palace",
        "XP4_Quake": "Epicenter",
        "XP4_FD": "Markaz Monolith",
        "XP4_Rubble": "Talah Market",
        "XP5_001": "Operation Riverside",
        "XP5_002": "Nebandan Flats",
        "XP5_003": "Kiasar Railroad",
        "XP5_004": "Sabalan Pipeline",
    },
    "BF2142": {
        "belgrade": "Belgrade",
        "bridge_at_remagen": "Bridge at Remagen",
        "camp_gibraltar": "Camp Gibraltar",
        "cerbere_landing": "Cerbere Landing",
        "fall_of_berlin": "Fall of Berlin",
        "highway_tampa": "Highway Tampa",
        "liberation_of_leipzig": "Liberation of Leipzig",
        "minsk": "Minsk",
        "molokai": "Molokai",
        "operation_blue_pearl": "Operation Blue Pearl",
        "operation_shingle": "Operation Shingle",
        "port_bavaria": "Port Bavaria",
        "shuhia_taiba": "Shuhia Taiba",
        "sidi_power_plant": "Sidi Power Plant",
        "strike_at_karkand": "Strike at Karkand",
        "suez_canal": "Suez Canal",
        "tunis_harbor": "Tunis Harbor",
        "verdun": "Verdun",
        "wake_island_2142": "Wake Island 2142",
        "yellow_knife": "Yellow Knife",
    }
}

gamemode_names = {
    "BF3": {
        "ConquestLarge0": "Conquest Large",
        "ConquestSmall0": "Conquest",
        "ConquestAssaultLarge0": "Conquest Assault Large",
        "ConquestAssaultSmall0": "Conquest Assault",
        "ConquestAssaultSmall1": "Conquest Assault: Day 2",
        "RushLarge0": "Rush",
        "SquadRush0": "Squad Rush",
        "SquadDeathMatch0": "Squad Deathmatch",
        "TeamDeathMatch0": "Team Deathmatch",
        "TeamDeathMatchC0": "Team DM Close Quarters",
        "Domination0": "Conquest Domination",
        "GunMaster0": "Gun Master",
        "TankSuperiority0": "Tank Superiority",
        "Scavenger0": "Scavenger",
        "CaptureTheFlag0": "Capture the Flag",
        "AirSuperiority0": "Air Superiority",
    },
    "BF2142": {
        "gpm_nv": "No Vehicle",
        "gpm_cq": "Conquest",
        "gpm_coop": "Co-Op",
        "gpm_ti": "Titan",
        "gpm_ca": "Conquest Assault"
    }
}
